# Generated by Django 4.2.6 on 2023-11-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_cinecritix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='perfil/', verbose_name='Imagen'),
        ),
    ]
