# Generated by Django 4.2.6 on 2023-10-22 02:05

from django.db import migrations, models
import users_cinecritix.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_cinecritix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.TextField(error_messages={'unique': 'Ya hay un usuario registrado con este documento'}, max_length=11, unique=True, validators=[users_cinecritix.models.CustomUser.validate_min_length]),
        ),
    ]
