# Generated by Django 4.2.6 on 2023-11-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_cinecritix', '0002_alter_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfil/usuario_default.png', max_length=255, null=True, upload_to='perfil/', verbose_name='Imagen'),
        ),
    ]
