# Generated by Django 4.0.2 on 2023-10-22 03:16

from django.db import migrations, models
import users_cinecritix.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_cinecritix', '0003_customuser_apellido_customuser_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='documento',
            field=models.TextField(error_messages={'unique': 'Ya hay un usuario registrado con este documento'}, max_length=11, unique=True, validators=[users_cinecritix.models.CustomUser.validate_min_length]),
        ),
    ]
