# Generated by Django 4.2.6 on 2023-11-25 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_passwordreset', '0003_allow_blank_and_null_fields'),
        ('users_cinecritix', '0003_alter_customuser_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedResetPasswordToken',
            fields=[
                ('resetpasswordtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_rest_passwordreset.resetpasswordtoken')),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('django_rest_passwordreset.resetpasswordtoken',),
        ),
    ]
