# Generated by Django 4.2.6 on 2023-11-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_cinecritix', '0004_extendedresetpasswordtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedResetPasswordToken',
        ),
    ]
