# Generated by Django 4.0.2 on 2023-10-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_cinecritix', '0004_alter_customuser_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actor', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('biografia', models.TextField()),
                ('nacionalidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=30)),
                ('descripcion_genero', models.CharField(max_length=300)),
            ],
        ),
    ]
