# Generated by Django 4.2.6 on 2023-11-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_cinecritix', '0005_delete_extendedresetpasswordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deactivated_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
