# Generated by Django 4.2.6 on 2023-11-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_cinecritix', '0006_customuser_deactivated_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('count_integer', models.IntegerField(default=0, verbose_name='Contador de intentos')),
            ],
        ),
    ]
