# Generated by Django 3.2.19 on 2023-11-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_cinecritix', '0007_extendtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='https://ff21bd761b567f2b564cc8785b9362ab18324393e6a0137684d4c29-apidata.googleusercontent.com/download/storage/v1/b/bucket-final-este-si-con-fe/o/perfil%2Fusuario_default.png?jk=AanfhSAXNVJgzmzAzVhzfng2fc3k6Py6yO2pUxkSK0Q8ryVmIpGpBwC7hEbF8RQ51x7MiscrU5TxY6Bx_Qu0N9Is2DJg-mgiUwtksIBFLjOoOfFm5-uhEjdVao2uBGNn7MYh9m8C56Dyblr0eDtDz-5QAW5UR1WQiPW0U13nk_H8JCmLNNiFjdtYo2RERi7ldS882Tkj7Htg2cwkWZHwPB3x89JBZPkYhTeK2wUYMF5aqWuh18p_6qojrliC7JWRwq9tGSKLApTdS2d5uWyx-IYd_PQxYoCCXY--ckkQ74eJ-7hqMGXkM1yLKW3RZIsG3q329hFozUr9MN_zo0OfPx9SJGr-eqnYGK7ujoKeD2ai2sdfHyB67CwYHftLK5nocnmDb5jhOPbGi3X8U_v-XlKLcz8kNVAM7LSW6pc5LAy8S_CUmI0WZwvz6CmK4vdK699NhtPgbhYmHPzX79FzfaAUekDHATpE6ZNqOUAfjTJhQx7FxuuceRBgaAqTQfs-yuAuTpXFQzIMdwjka4altnwX5pS9imuqK0OV67U1XCy_Kza2OhsqQLvVK4Iha95XMPDXmWQHmUBCsJ2hLRhdWvpl_gA16dkBhaAa70m3Ot2zfl4fuVul5KbihSoDZeuCZ34DtsC-sbFk5Sx0EAZK4kViqjkFBwJIzq7sUSJUYh-CZgkIzM2t6MCFuZwKUaPszG5VHc1B_IjgAWoqQwA8Ssc6i_rjofQ5xYQhjpSDudKDA3GBveiWZSVds35aLdOANnk4l1Qbao_fGqq2-cpprtE565XYmAagqqG-UV-1GtzX1xHCUTnAD8AcicJrgzCG5ZYdsF-C3FSKzKFMCcB5xsq0CWUCouvUqG7OBNruK8nMJuEng1tf8cHQ7cGLz18cGp6atBrcwD7bext3qE0ksIN2EB9txqCYfTtijRCg0DfkhqwiWYPqV6PxzU2j5RCTYn6Sl-malEnB1jdKME7JJPOyikqa6XJsKaGswa83m4XEIBCg3unRH0BtA90VBW6UZWh1l1aBL9YLUyk04jD-JDchGKdLo9jwHlqZXepoMJZS0dhU_Y2i8eUmRvNFw1CgqZQX8Py9ftcCz8N3TnDwZ1OUIyDPx7kxUtEhA_O1Lz0BMl0h16LSu1URrzHSUyFm62ZhbVvF9pCfhRfv_oYNX-5KVoPH64B3uqlPhevrj06NxT5z9kuIN5ouDbN2qmAJoC--61zptTuDzLIaUshamhr7LUHT7ll0LjsETlKGii4JREabr75XG25yOyzAKZ8TDpnWfYpYdYygdxmMfPdzJbgu_OYhVHwS31x3RgpwPoIHUIkQp7fxG8mtdwpK3HssQkX9r8JdO5gPHW4qpS_1TDufbllxf9HV3W1_2Lzv-9vaUWCD1weqpRpM5T_v2hRbXA&isca=1', max_length=1000, null=True, upload_to='perfil/', verbose_name='Imagen'),
        ),
    ]
