# Generated by Django 4.2.6 on 2023-11-24 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_cinecritix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pelicula', models.CharField(max_length=30, unique=True)),
                ('director_pelicula', models.CharField(max_length=30)),
                ('sipnosis_pelicula', models.CharField(max_length=250)),
                ('duracion_pelicula', models.IntegerField(default=0)),
                ('fecha_estreno_pelicula', models.DateField()),
                ('portada_pelicula', models.ImageField(null=True, upload_to='')),
                ('actores', models.ManyToManyField(related_name='peliculas_actuadas', to='users_cinecritix.actor')),
                ('genero', models.ManyToManyField(related_name='genero_peliculas', to='users_cinecritix.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion_pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntuacion', models.IntegerField(default=0)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_peliculas_cinecritix.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito_pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('pelicula', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_peliculas_cinecritix.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios_pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentario', models.TextField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_peliculas_cinecritix.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
