# Generated by Django 4.2.6 on 2023-10-22 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_peliculas_cinecritix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito_pelicula',
            name='pelicula',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='portada_pelicula',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='favorito_pelicula',
            name='pelicula',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='modulo_peliculas_cinecritix.pelicula'),
        ),
    ]
