# Generated by Django 4.2.6 on 2023-12-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_peliculas_cinecritix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen_pelicula',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='peliculas/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='link_pelicula',
            field=models.TextField(blank=True, default='No se encontró link', null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='link_trailer',
            field=models.TextField(blank=True, default='No se encontró link', null=True),
        ),
    ]
