# Generated by Django 4.2.6 on 2023-12-15 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_peliculas_cinecritix', '0003_remove_pelicula_portada_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='director_pelicula',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno_pelicula',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='sipnosis_pelicula',
            field=models.TextField(max_length=250),
        ),
    ]
