# Generated by Django 4.2.6 on 2023-11-24 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_cinecritix', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_capitulo', models.CharField(max_length=250)),
                ('numero_capitulo', models.IntegerField(default=0)),
                ('sipnosis_capitulo', models.CharField(max_length=250)),
                ('duracion_capitulo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_serie', models.CharField(max_length=30, unique=True)),
                ('director_serie', models.CharField(max_length=30)),
                ('sipnosis_serie', models.CharField(max_length=250)),
                ('fecha_estreno_serie', models.DateField()),
                ('actores', models.ManyToManyField(related_name='series_actuadas', to='users_cinecritix.actor')),
                ('generos', models.ManyToManyField(related_name='generos_serie', to='users_cinecritix.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipnosis_temporada', models.CharField(max_length=250)),
                ('capitulos_temporada', models.IntegerField(default=0)),
                ('id_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_series_cinecritix.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion_serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntuacion', models.IntegerField(default=0)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_series_cinecritix.serie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion_capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('puntuacion', models.IntegerField(default=0)),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_series_cinecritix.capitulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito_serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('serie', models.ManyToManyField(related_name='peliculas_like', to='modulo_series_cinecritix.serie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito_capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('capitulo', models.ManyToManyField(related_name='peliculas_like', to='modulo_series_cinecritix.capitulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios_serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentario', models.TextField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_series_cinecritix.serie')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios_capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentario', models.TextField()),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_series_cinecritix.capitulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='id_temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_series_cinecritix.temporada'),
        ),
    ]
