# Generated by Django 4.2.6 on 2023-12-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_series_cinecritix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='imagen_serie',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='series/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='serie',
            name='link_serie',
            field=models.TextField(blank=True, default='No se encontró link', null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='link_trailer',
            field=models.TextField(blank=True, default='No se encontró link', null=True),
        ),
        migrations.AddField(
            model_name='temporada',
            name='imagen_temporada',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='temporada/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='nombre_temporada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='temporadas_nombre', to='modulo_series_cinecritix.serie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporada',
            name='id_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas_id', to='modulo_series_cinecritix.serie'),
        ),
    ]
